// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xlemleldxfgarrcoffkq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhsZW1sZWxkeGZnYXJyY29mZmtxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY3MDQ4MTIsImV4cCI6MjA2MjI4MDgxMn0.91Xoso5UE_TvdRQh2iBCCR0yiZYsU0o6iiq5WlWHjdk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);